/*
Navicat Oracle Data Transfer
Oracle Client Version : 11.2.0.1.0

Source Server         : Test
Source Server Version : 120100
Source Host           : 192.168.10.167:1521
Source Schema         : CRM_TEST

Target Server Type    : ORACLE
Target Server Version : 120100
File Encoding         : 65001

Date: 2017-09-05 10:05:46
*/


-- ----------------------------
-- Table structure for TT_BUDGET_PERIOD
-- ----------------------------
DROP TABLE "CRM_TEST"."TT_BUDGET_PERIOD";
CREATE TABLE "CRM_TEST"."TT_BUDGET_PERIOD" (
"ID" VARCHAR2(32 BYTE) NOT NULL ,
"YEAR" VARCHAR2(4 BYTE) NULL ,
"MONTH" VARCHAR2(2 BYTE) NULL ,
"QUARTER" VARCHAR2(1 BYTE) NULL ,
"YEAR_MONTH" VARCHAR2(7 BYTE) NULL ,
"ORG_CODE" VARCHAR2(50 BYTE) NULL ,
"ORG_NAME" VARCHAR2(50 BYTE) NULL ,
"COST_TYPE_CODE" VARCHAR2(50 BYTE) NULL ,
"COST_TYPE_NAME" VARCHAR2(50 BYTE) NULL ,
"CHANNEL_CODE" VARCHAR2(50 BYTE) NULL ,
"CHANNEL_NAME" VARCHAR2(50 BYTE) NULL ,
"CUSTOMER_CODE" VARCHAR2(50 BYTE) NULL ,
"CUSTOMER_NAME" VARCHAR2(200 BYTE) NULL ,
"PRODUCT_CODE" VARCHAR2(50 BYTE) NULL ,
"PRODUCT_NAME" VARCHAR2(200 BYTE) NULL ,
"AMOUNT" NUMBER(10,2) NULL ,
"BUDGET_PERIOD_CODE" VARCHAR2(50 BYTE) NULL ,
"CREATE_DATE" TIMESTAMP(6)  NULL ,
"CREATE_NAME" VARCHAR2(100 BYTE) NULL ,
"UPDATE_DATE" TIMESTAMP(6)  NULL ,
"UPDATE_NAME" VARCHAR2(100 BYTE) NULL ,
"ACCOUNT_CODE" VARCHAR2(32 BYTE) NULL ,
"ACCOUNT_NAME" VARCHAR2(32 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "CRM_TEST"."TT_BUDGET_PERIOD"."ID" IS '逻辑主键id';
COMMENT ON COLUMN "CRM_TEST"."TT_BUDGET_PERIOD"."YEAR" IS '年（yyyy）';
COMMENT ON COLUMN "CRM_TEST"."TT_BUDGET_PERIOD"."MONTH" IS '月（MM）';
COMMENT ON COLUMN "CRM_TEST"."TT_BUDGET_PERIOD"."QUARTER" IS '季度';
COMMENT ON COLUMN "CRM_TEST"."TT_BUDGET_PERIOD"."YEAR_MONTH" IS '年月（yyyy-MM）';
COMMENT ON COLUMN "CRM_TEST"."TT_BUDGET_PERIOD"."ORG_CODE" IS '组织编码';
COMMENT ON COLUMN "CRM_TEST"."TT_BUDGET_PERIOD"."ORG_NAME" IS '组织名称';
COMMENT ON COLUMN "CRM_TEST"."TT_BUDGET_PERIOD"."COST_TYPE_CODE" IS '费用类型编码';
COMMENT ON COLUMN "CRM_TEST"."TT_BUDGET_PERIOD"."COST_TYPE_NAME" IS '费用类型名称';
COMMENT ON COLUMN "CRM_TEST"."TT_BUDGET_PERIOD"."CHANNEL_CODE" IS '渠道编码';
COMMENT ON COLUMN "CRM_TEST"."TT_BUDGET_PERIOD"."CHANNEL_NAME" IS '渠道名称';
COMMENT ON COLUMN "CRM_TEST"."TT_BUDGET_PERIOD"."CUSTOMER_CODE" IS '客户编码';
COMMENT ON COLUMN "CRM_TEST"."TT_BUDGET_PERIOD"."CUSTOMER_NAME" IS '客户名称';
COMMENT ON COLUMN "CRM_TEST"."TT_BUDGET_PERIOD"."PRODUCT_CODE" IS '产品编码';
COMMENT ON COLUMN "CRM_TEST"."TT_BUDGET_PERIOD"."PRODUCT_NAME" IS '产品名称';
COMMENT ON COLUMN "CRM_TEST"."TT_BUDGET_PERIOD"."AMOUNT" IS '初期金额';
COMMENT ON COLUMN "CRM_TEST"."TT_BUDGET_PERIOD"."BUDGET_PERIOD_CODE" IS '期初预算编码，使用编码规则自动生成';
COMMENT ON COLUMN "CRM_TEST"."TT_BUDGET_PERIOD"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "CRM_TEST"."TT_BUDGET_PERIOD"."CREATE_NAME" IS '创建人';
COMMENT ON COLUMN "CRM_TEST"."TT_BUDGET_PERIOD"."UPDATE_DATE" IS '修改时间';
COMMENT ON COLUMN "CRM_TEST"."TT_BUDGET_PERIOD"."UPDATE_NAME" IS '修改人';
COMMENT ON COLUMN "CRM_TEST"."TT_BUDGET_PERIOD"."ACCOUNT_CODE" IS '财务科目(预算科目)编码';
COMMENT ON COLUMN "CRM_TEST"."TT_BUDGET_PERIOD"."ACCOUNT_NAME" IS '财务科目(预算科目)名称';

-- ----------------------------
-- Checks structure for table TT_BUDGET_PERIOD
-- ----------------------------
ALTER TABLE "CRM_TEST"."TT_BUDGET_PERIOD" ADD CHECK ("ID" IS NOT NULL);
