/*
Navicat Oracle Data Transfer
Oracle Client Version : 11.2.0.1.0

Source Server         : Cust
Source Server Version : 120100
Source Host           : 192.168.10.167:1521
Source Schema         : CRM_CUST

Target Server Type    : ORACLE
Target Server Version : 120100
File Encoding         : 65001

Date: 2017-08-31 09:14:54
*/


-- ----------------------------
-- Table structure for TT_FINANCIAL_ACCOUNT
-- ----------------------------
DROP TABLE "CRM_CUST"."TT_FINANCIAL_ACCOUNT";
CREATE TABLE "CRM_CUST"."TT_FINANCIAL_ACCOUNT" (
"ID" VARCHAR2(32 BYTE) NOT NULL ,
"ACCOUNT_CODE" VARCHAR2(255 BYTE) NULL ,
"ACCOUNT_NAME" VARCHAR2(255 BYTE) NULL ,
"FINANCIAL_CODE" VARCHAR2(50 BYTE) NULL ,
"REMARK" VARCHAR2(200 BYTE) NULL ,
"CREATE_DATE" TIMESTAMP(0)  NULL ,
"CREATE_NAME" VARCHAR2(100 BYTE) NULL ,
"UPDATE_DATE" TIMESTAMP(0)  NULL ,
"UPDATE_NAME" VARCHAR2(100 BYTE) NULL ,
"ENABLE_STATUS" NUMBER(1) NULL ,
"ACCOUNT_TYPE" VARCHAR2(5 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "CRM_CUST"."TT_FINANCIAL_ACCOUNT" IS '财务科目';
COMMENT ON COLUMN "CRM_CUST"."TT_FINANCIAL_ACCOUNT"."ID" IS '逻辑主键';
COMMENT ON COLUMN "CRM_CUST"."TT_FINANCIAL_ACCOUNT"."ACCOUNT_CODE" IS '科目编码，使用规则自动生成';
COMMENT ON COLUMN "CRM_CUST"."TT_FINANCIAL_ACCOUNT"."ACCOUNT_NAME" IS '科目名称';
COMMENT ON COLUMN "CRM_CUST"."TT_FINANCIAL_ACCOUNT"."FINANCIAL_CODE" IS '财务编码，一般与erp系统财务编码对应';
COMMENT ON COLUMN "CRM_CUST"."TT_FINANCIAL_ACCOUNT"."REMARK" IS '备注';
COMMENT ON COLUMN "CRM_CUST"."TT_FINANCIAL_ACCOUNT"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "CRM_CUST"."TT_FINANCIAL_ACCOUNT"."CREATE_NAME" IS '创建人';
COMMENT ON COLUMN "CRM_CUST"."TT_FINANCIAL_ACCOUNT"."UPDATE_DATE" IS '修改时间';
COMMENT ON COLUMN "CRM_CUST"."TT_FINANCIAL_ACCOUNT"."UPDATE_NAME" IS '修改人';
COMMENT ON COLUMN "CRM_CUST"."TT_FINANCIAL_ACCOUNT"."ENABLE_STATUS" IS '是否启用，1是，0否';
COMMENT ON COLUMN "CRM_CUST"."TT_FINANCIAL_ACCOUNT"."ACCOUNT_TYPE" IS '科目类别';

-- ----------------------------
-- Checks structure for table TT_FINANCIAL_ACCOUNT
-- ----------------------------
ALTER TABLE "CRM_CUST"."TT_FINANCIAL_ACCOUNT" ADD CHECK ("ID" IS NOT NULL);
