SELECT
t1.BILL_ITEM AS billItem,
t1.BILL_NUM AS billNum,
t1.LOGSYS AS logsys,
t1."/BIC/ZC_ITEM" AS bicZcItem,
t1."/BIC/ZC_CFBZ" AS bicZcCfbz,
t1."/BIC/ZCRM_GRP" AS bicZcrmGrp,
t1."/BIC/ZCUSTOMER" AS bicZcustomer,
t1."/BIC/ZC_SYB" AS bicZcSyb,
t1.FISCVARNT AS fiscvarnt,
t1.STAT_CURR AS statCurr,
t1.DOC_CURRCY AS docCurrcy,
t1.LOC_CURRCY AS locCurrcy,
t1.DENOMINTR AS denomintr,
t1.NUMERATOR AS numerator,
t1.NO_INV_IT AS noInvIt,
t1.BASE_UOM AS baseUom,
t1.UNIT_OF_WT AS unitOfWt,
t1.VOLUMEUNIT AS volumeunit,
t1.SALES_UNIT AS salesUnit,
t1.GRS_WGT_DL AS grsWgtDl,
t1.INV_QTY AS invQty,
t1.BILL_QTY AS billQty,
t1.TAX_AMOUNT AS taxAmount,
t1.NET_WGT_DL AS netWgtDl,
t1.COST AS cost,
t1.SUBTOTAL_1 AS subtotal_1,
t1.SUBTOTAL_2 AS subtotal_2,
t1.SUBTOTAL_3 AS subtotal_3,
t1.SUBTOTAL_4 AS subtotal_4,
t1.SUBTOTAL_5 AS subtotal_5,
t1.SUBTOTAL_6 AS subtotal_6,
t1.NETVAL_INV AS netvalInv,
t1.GROSS_VAL AS grossVal,
t1.COMP_CODE AS compCode,
t1.BILL_TYPE AS billType,
t1.STOR_LOC AS storLoc,
t1.ITEM_CATEG AS itemCateg,
t1.SALES_OFF AS salesOff,
t1.SHIP_POINT AS shipPoint,
t1.PLANT AS plant,
t1.SALESORG AS salesorg,
t1.CO_AREA AS coArea,
t1.STORNO AS storno,
t1.BILL_CAT AS billCat,
t1.CUST_GROUP AS custGroup,
t1.ITM_TYPE AS itmType,
t1.DOC_CATEG AS docCateg,
t1.DISTR_CHAN AS distrChan,
t1.DIVISION AS division,
t1.DIV_HEAD AS divHead,
t1.BILL_RULE AS billRule,
t1.SALES_DIST AS salesDist,
t1.MATL_GROUP AS matlGroup,
t1.SALES_GRP AS salesGrp,
t1.BWAPPLNM AS bwapplnm,
t1.CREATEDON AS createdon,
t1.CH_ON AS chOn,
t1.BILL_DATE AS billDate,
t1.S_ORD_ITEM AS sOrdItem,
t1.REFER_ITM AS referItm,
t1.PROCESSKEY AS processkey,
t1.MATERIAL AS material,
t1.SOLD_TO AS soldTo,
t1.PAYER AS payer,
t1.DOC_NUMBER AS docNumber,
t1.SALESDEAL AS salesdeal,
t1.BILLTOPRTY AS billtoprty,
t1.SHIP_TO AS shipTo,
t1.REFER_DOC AS referDoc,
t1.COSTCENTER AS costcenter,
t1."/BIC/ZC_ERDAT1" AS bicZcErdat1,
t1."/BIC/ZK_KZWI3" AS bicZkKzwi3,
t1."/BIC/ZK_KZWI4" AS bicZkKzwi4,
t1."/BIC/ZK_KZWI5" AS bicZkKzwi5,
t1."/BIC/ZK_KZWI6" AS bicZkKzwi6,
t1."/BIC/ZC_BSTNK" AS bicZcBstnk,
t1."/BIC/ZK_KZWI2" AS bicZkKzwi2,
t1."/BIC/ZK_TLDZ" AS bicZkTldz,
t1."/BIC/ZK_KZWI7" AS bicZkKzwi7,
t1."/BIC/ZK_XSSR1" AS bicZkXssr1,
t1."/BIC/ZK_XSSR" AS bicZkXssr,
t1."/BIC/ZC_BMBH" AS bicZcBmbh,
(select org_name from tm_org where org_code=t1."/BIC/ZC_SYB") AS sybName,
(select customer_name from tm_customer where t1.SOLD_TO = customer_code) AS customerName,
(select id from tm_org where id=(select org_id from tm_customer where t1.SOLD_TO = customer_code)) AS orgId,
(select org_name from tm_org where id=(select org_id from tm_customer where t1.SOLD_TO = customer_code)) AS orgName,
(select org_code from tm_org where id=(select org_id from tm_customer where t1.SOLD_TO = customer_code)) AS orgCode,
(select org_code from tm_org where id=(select parent_id from tm_org where id=(select org_id from tm_customer where t1.SOLD_TO = customer_code))) AS parentOrgCode,
(select org_name from tm_org where id=(select parent_id from tm_org where id=(select org_id from tm_customer where t1.SOLD_TO = customer_code))) AS parentOrgName,
(select org_name from tm_org where id=(select parent_id from tm_org where id=((select parent_id from tm_org where id=(select org_id from tm_customer where t1.SOLD_TO = customer_code))))) AS grandOrgName,
(select org_code from tm_org where id=(select parent_id from tm_org where id=((select parent_id from tm_org where id=(select org_id from tm_customer where t1.SOLD_TO = customer_code))))) AS grandOrgCode
FROM "/BIC/OHZ_0HD_02" t1
WHERE 1=1
